=== rookiefly/shardbatis/trunk/src/main/resources/com/google/code/shardbatis/builder/shardbatis-config.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT shardingConfig (ignoreList?,parseList?,strategy*)>
<!ELEMENT ignoreList (value+)>
<!ELEMENT parseList (value+)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT strategy EMPTY>
<!ATTLIST strategy
tableName CDATA #REQUIRED
strategyClass CDATA #REQUIRED
>

=== rookiefly/shardbatis/src/test/resources/test_config_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE shardingConfig PUBLIC "-//shardbatis.googlecode.com//DTD Shardbatis 2.0//EN"
        "http://shardbatis.googlecode.com/dtd/shardbatis-config.dtd">
<shardingConfig>
    <ignoreList>
        <value>ignoreId1</value>
        <value>ignoreId2</value>
        <value> <![CDATA[ <testid ]]></value>
    </ignoreList>

    <parseList>
        <value>parseId</value>
        <value> <![CDATA[ parseid>2]]></value>
    </parseList>

    <strategy tableName="test_table1" strategyClass="com.google.code.shardbatis.strategy.impl.TestShardStrategyImpl"/>
    <strategy tableName="test_table2" strategyClass="com.google.code.shardbatis.strategy.impl.TestShardStrategyImpl"/>
</shardingConfig>
